// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/golang-jwt/jwt/v5"
	"github.com/gosoline-project/httpserver/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewJwtTokenHandler creates a new instance of JwtTokenHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJwtTokenHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *JwtTokenHandler {
	mock := &JwtTokenHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JwtTokenHandler is an autogenerated mock type for the JwtTokenHandler type
type JwtTokenHandler struct {
	mock.Mock
}

type JwtTokenHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *JwtTokenHandler) EXPECT() *JwtTokenHandler_Expecter {
	return &JwtTokenHandler_Expecter{mock: &_m.Mock}
}

// Sign provides a mock function for the type JwtTokenHandler
func (_mock *JwtTokenHandler) Sign(user auth.SignUserInput) (*string, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.SignUserInput) (*string, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.SignUserInput) *string); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(auth.SignUserInput) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JwtTokenHandler_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type JwtTokenHandler_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - user auth.SignUserInput
func (_e *JwtTokenHandler_Expecter) Sign(user interface{}) *JwtTokenHandler_Sign_Call {
	return &JwtTokenHandler_Sign_Call{Call: _e.mock.On("Sign", user)}
}

func (_c *JwtTokenHandler_Sign_Call) Run(run func(user auth.SignUserInput)) *JwtTokenHandler_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.SignUserInput
		if args[0] != nil {
			arg0 = args[0].(auth.SignUserInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JwtTokenHandler_Sign_Call) Return(s *string, err error) *JwtTokenHandler_Sign_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *JwtTokenHandler_Sign_Call) RunAndReturn(run func(user auth.SignUserInput) (*string, error)) *JwtTokenHandler_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// SignClaims provides a mock function for the type JwtTokenHandler
func (_mock *JwtTokenHandler) SignClaims(claims auth.Claims) (*string, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for SignClaims")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.Claims) (*string, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.Claims) *string); ok {
		r0 = returnFunc(claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(auth.Claims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JwtTokenHandler_SignClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignClaims'
type JwtTokenHandler_SignClaims_Call struct {
	*mock.Call
}

// SignClaims is a helper method to define mock.On call
//   - claims auth.Claims
func (_e *JwtTokenHandler_Expecter) SignClaims(claims interface{}) *JwtTokenHandler_SignClaims_Call {
	return &JwtTokenHandler_SignClaims_Call{Call: _e.mock.On("SignClaims", claims)}
}

func (_c *JwtTokenHandler_SignClaims_Call) Run(run func(claims auth.Claims)) *JwtTokenHandler_SignClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.Claims
		if args[0] != nil {
			arg0 = args[0].(auth.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JwtTokenHandler_SignClaims_Call) Return(s *string, err error) *JwtTokenHandler_SignClaims_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *JwtTokenHandler_SignClaims_Call) RunAndReturn(run func(claims auth.Claims) (*string, error)) *JwtTokenHandler_SignClaims_Call {
	_c.Call.Return(run)
	return _c
}

// Valid provides a mock function for the type JwtTokenHandler
func (_mock *JwtTokenHandler) Valid(jwtToken string) (bool, *jwt.Token, error) {
	ret := _mock.Called(jwtToken)

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 bool
	var r1 *jwt.Token
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, *jwt.Token, error)); ok {
		return returnFunc(jwtToken)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(jwtToken)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) *jwt.Token); ok {
		r1 = returnFunc(jwtToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*jwt.Token)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(jwtToken)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// JwtTokenHandler_Valid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valid'
type JwtTokenHandler_Valid_Call struct {
	*mock.Call
}

// Valid is a helper method to define mock.On call
//   - jwtToken string
func (_e *JwtTokenHandler_Expecter) Valid(jwtToken interface{}) *JwtTokenHandler_Valid_Call {
	return &JwtTokenHandler_Valid_Call{Call: _e.mock.On("Valid", jwtToken)}
}

func (_c *JwtTokenHandler_Valid_Call) Run(run func(jwtToken string)) *JwtTokenHandler_Valid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JwtTokenHandler_Valid_Call) Return(b bool, token *jwt.Token, err error) *JwtTokenHandler_Valid_Call {
	_c.Call.Return(b, token, err)
	return _c
}

func (_c *JwtTokenHandler_Valid_Call) RunAndReturn(run func(jwtToken string) (bool, *jwt.Token, error)) *JwtTokenHandler_Valid_Call {
	_c.Call.Return(run)
	return _c
}
