// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTokenBearer creates a new instance of TokenBearer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenBearer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenBearer {
	mock := &TokenBearer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenBearer is an autogenerated mock type for the TokenBearer type
type TokenBearer struct {
	mock.Mock
}

type TokenBearer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenBearer) EXPECT() *TokenBearer_Expecter {
	return &TokenBearer_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type TokenBearer
func (_mock *TokenBearer) GetToken() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// TokenBearer_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type TokenBearer_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
func (_e *TokenBearer_Expecter) GetToken() *TokenBearer_GetToken_Call {
	return &TokenBearer_GetToken_Call{Call: _e.mock.On("GetToken")}
}

func (_c *TokenBearer_GetToken_Call) Run(run func()) *TokenBearer_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenBearer_GetToken_Call) Return(s string) *TokenBearer_GetToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *TokenBearer_GetToken_Call) RunAndReturn(run func() string) *TokenBearer_GetToken_Call {
	_c.Call.Return(run)
	return _c
}
