package httpserver

import "net/textproto"

const (
	ContentTypeJson            = "application/json; charset=utf-8"
	ContentTypeApplicationJson = "application/json"
	ContentTypeTextPlain       = "text/plain; charset=utf-8"
	ContentTypeHtml            = "text/html; charset=utf-8"
	ContentTypeEventStream     = "text/event-stream"
	ContentTypeFormURLEncoded  = "application/x-www-form-urlencoded"

	HeaderAccept                        = "Accept"
	HeaderAcceptCharset                 = "Accept-Charset"
	HeaderAcceptDatetime                = "Accept-Datetime"
	HeaderAcceptEncoding                = "Accept-Encoding"
	HeaderAcceptLanguage                = "Accept-Language"
	HeaderAcceptPatch                   = "Accept-Patch"
	HeaderAcceptRanges                  = "Accept-Ranges"
	HeaderAccessControlAllowCredentials = "Access-Control-Allow-Credentials"
	HeaderAccessControlAllowHeaders     = "Access-Control-Allow-Headers"
	HeaderAccessControlAllowMethods     = "Access-Control-Allow-Methods"
	HeaderAccessControlAllowOrigin      = "Access-Control-Allow-Origin"
	HeaderAccessControlExposeHeaders    = "Access-Control-Expose-Headers"
	HeaderAccessControlMaxAge           = "Access-Control-Max-Age"
	HeaderAccessControlRequestHeaders   = "Access-Control-Request-Headers"
	HeaderAccessControlRequestMethod    = "Access-Control-Request-Method"
	HeaderAllow                         = "Allow"
	HeaderAuthorization                 = "Authorization"
	HeaderCacheControl                  = "Cache-Control"
	HeaderConnection                    = "Connection"
	HeaderContentDisposition            = "Content-Disposition"
	HeaderContentEncoding               = "Content-Encoding"
	HeaderContentLanguage               = "Content-Language"
	HeaderContentLength                 = "Content-Length"
	HeaderContentLocation               = "Content-Location"
	HeaderContentMD5                    = "Content-MD5"
	HeaderContentRange                  = "Content-Range"
	HeaderContentSecurityPolicy         = "Content-Security-Policy"
	HeaderContentType                   = "Content-Type"
	HeaderCookie                        = "Cookie"
	HeaderDoNotTrack                    = "DNT"
	HeaderETag                          = "ETag"
	HeaderExpires                       = "Expires"
	HeaderIfMatch                       = "If-Match"
	HeaderIfModifiedSince               = "If-Modified-Since"
	HeaderIfNoneMatch                   = "If-None-Match"
	HeaderIfRange                       = "If-Range"
	HeaderIfUnmodifiedSince             = "If-Unmodified-Since"
	HeaderLastModified                  = "Last-Modified"
	HeaderLink                          = "Link"
	HeaderLocation                      = "Location"
	HeaderMaxForwards                   = "Max-Forwards"
	HeaderOrigin                        = "Origin"
	HeaderP3P                           = "P3P"
	HeaderPragma                        = "Pragma"
	HeaderProxyAuthenticate             = "Proxy-Authenticate"
	HeaderProxyAuthorization            = "Proxy-Authorization"
	HeaderRange                         = "Range"
	HeaderReferer                       = "Referer"
	HeaderRefresh                       = "Refresh"
	HeaderRequestId                     = "X-Request-Id"
	HeaderRetryAfter                    = "Retry-After"
	HeaderServer                        = "Server"
	HeaderSessionId                     = "X-Session-Id"
	HeaderSetCookie                     = "Set-Cookie"
	HeaderStrictTransportSecurity       = "Strict-Transport-Security"
	HeaderTE                            = "TE"
	HeaderTransferEncoding              = "Transfer-Encoding"
	HeaderUpgrade                       = "Upgrade"
	HeaderUserAgent                     = "User-Agent"
	HeaderVary                          = "Vary"
	HeaderVia                           = "Via"
	HeaderWarning                       = "Warning"
	HeaderWWWAuthenticate               = "WWW-Authenticate"
	HeaderXContentSecurityPolicy        = "X-Content-Security-Policy"
	HeaderXContentTypeOptions           = "X-Content-Type-Options"
	HeaderXCSRFToken                    = "X-CSRF-Token"
	HeaderXForwardedFor                 = "X-Forwarded-For"
	HeaderXForwardedProto               = "X-Forwarded-Proto"
	HeaderXFrameOptions                 = "X-Frame-Options"
	HeaderXHTTPMethodOverride           = "X-HTTP-Method-Override"
	HeaderXPoweredBy                    = "X-Powered-By"
	HeaderXRatelimitLimit               = "X-Ratelimit-Limit"
	HeaderXRatelimitRemaining           = "X-Ratelimit-Remaining"
	HeaderXRatelimitReset               = "X-Ratelimit-Reset"
	HeaderXRealIP                       = "X-Real-IP"
	HeaderXRequestedWith                = "X-Requested-With"
	HeaderXUACompatible                 = "X-UA-Compatible"
	HeaderXWebKitCSP                    = "X-WebKit-CSP"
	HeaderXXSSProtection                = "X-XSS-Protection"

	HeaderValueBasicRealmFormat = "Basic realm=%q"
	HeaderValueClose            = "close"
	HeaderValueGzip             = "gzip"
	HeaderValueKeepAlive        = "keep-alive"
	HeaderValueNoCache          = "no-cache"
)

// Normalize formats the input header to the formation of "Xxx-Xxx".
func Normalize(header string) string {
	return textproto.CanonicalMIMEHeaderKey(header)
}
