// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ConnectionLifeCycleAdvisor is an autogenerated mock type for the ConnectionLifeCycleAdvisor type
type ConnectionLifeCycleAdvisor struct {
	mock.Mock
}

// ShouldCloseConnection provides a mock function with given fields: remoteAddr, headers
func (_m *ConnectionLifeCycleAdvisor) ShouldCloseConnection(remoteAddr string, headers http.Header) bool {
	ret := _m.Called(remoteAddr, headers)

	if len(ret) == 0 {
		panic("no return value specified for ShouldCloseConnection")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, http.Header) bool); ok {
		r0 = rf(remoteAddr, headers)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewConnectionLifeCycleAdvisor creates a new instance of ConnectionLifeCycleAdvisor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionLifeCycleAdvisor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionLifeCycleAdvisor {
	mock := &ConnectionLifeCycleAdvisor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
