// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewConnectionPressureManager creates a new instance of ConnectionPressureManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionPressureManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionPressureManager {
	mock := &ConnectionPressureManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConnectionPressureManager is an autogenerated mock type for the ConnectionPressureManager type
type ConnectionPressureManager struct {
	mock.Mock
}

type ConnectionPressureManager_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectionPressureManager) EXPECT() *ConnectionPressureManager_Expecter {
	return &ConnectionPressureManager_Expecter{mock: &_m.Mock}
}

// CloseOldestIdleConnection provides a mock function for the type ConnectionPressureManager
func (_mock *ConnectionPressureManager) CloseOldestIdleConnection() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseOldestIdleConnection")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConnectionPressureManager_CloseOldestIdleConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseOldestIdleConnection'
type ConnectionPressureManager_CloseOldestIdleConnection_Call struct {
	*mock.Call
}

// CloseOldestIdleConnection is a helper method to define mock.On call
func (_e *ConnectionPressureManager_Expecter) CloseOldestIdleConnection() *ConnectionPressureManager_CloseOldestIdleConnection_Call {
	return &ConnectionPressureManager_CloseOldestIdleConnection_Call{Call: _e.mock.On("CloseOldestIdleConnection")}
}

func (_c *ConnectionPressureManager_CloseOldestIdleConnection_Call) Run(run func()) *ConnectionPressureManager_CloseOldestIdleConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionPressureManager_CloseOldestIdleConnection_Call) Return(b bool, err error) *ConnectionPressureManager_CloseOldestIdleConnection_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *ConnectionPressureManager_CloseOldestIdleConnection_Call) RunAndReturn(run func() (bool, error)) *ConnectionPressureManager_CloseOldestIdleConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ConnState provides a mock function for the type ConnectionPressureManager
func (_mock *ConnectionPressureManager) ConnState(conn net.Conn, connState http.ConnState) {
	_mock.Called(conn, connState)
	return
}

// ConnectionPressureManager_ConnState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnState'
type ConnectionPressureManager_ConnState_Call struct {
	*mock.Call
}

// ConnState is a helper method to define mock.On call
//   - conn net.Conn
//   - connState http.ConnState
func (_e *ConnectionPressureManager_Expecter) ConnState(conn interface{}, connState interface{}) *ConnectionPressureManager_ConnState_Call {
	return &ConnectionPressureManager_ConnState_Call{Call: _e.mock.On("ConnState", conn, connState)}
}

func (_c *ConnectionPressureManager_ConnState_Call) Run(run func(conn net.Conn, connState http.ConnState)) *ConnectionPressureManager_ConnState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 net.Conn
		if args[0] != nil {
			arg0 = args[0].(net.Conn)
		}
		var arg1 http.ConnState
		if args[1] != nil {
			arg1 = args[1].(http.ConnState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ConnectionPressureManager_ConnState_Call) Return() *ConnectionPressureManager_ConnState_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConnectionPressureManager_ConnState_Call) RunAndReturn(run func(conn net.Conn, connState http.ConnState)) *ConnectionPressureManager_ConnState_Call {
	_c.Run(run)
	return _c
}

// IdleConnectionAvailable provides a mock function for the type ConnectionPressureManager
func (_mock *ConnectionPressureManager) IdleConnectionAvailable() <-chan struct{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IdleConnectionAvailable")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// ConnectionPressureManager_IdleConnectionAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdleConnectionAvailable'
type ConnectionPressureManager_IdleConnectionAvailable_Call struct {
	*mock.Call
}

// IdleConnectionAvailable is a helper method to define mock.On call
func (_e *ConnectionPressureManager_Expecter) IdleConnectionAvailable() *ConnectionPressureManager_IdleConnectionAvailable_Call {
	return &ConnectionPressureManager_IdleConnectionAvailable_Call{Call: _e.mock.On("IdleConnectionAvailable")}
}

func (_c *ConnectionPressureManager_IdleConnectionAvailable_Call) Run(run func()) *ConnectionPressureManager_IdleConnectionAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionPressureManager_IdleConnectionAvailable_Call) Return(valCh <-chan struct{}) *ConnectionPressureManager_IdleConnectionAvailable_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *ConnectionPressureManager_IdleConnectionAvailable_Call) RunAndReturn(run func() <-chan struct{}) *ConnectionPressureManager_IdleConnectionAvailable_Call {
	_c.Call.Return(run)
	return _c
}
