// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewErrorWithStatus creates a new instance of ErrorWithStatus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorWithStatus(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorWithStatus {
	mock := &ErrorWithStatus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ErrorWithStatus is an autogenerated mock type for the ErrorWithStatus type
type ErrorWithStatus struct {
	mock.Mock
}

type ErrorWithStatus_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorWithStatus) EXPECT() *ErrorWithStatus_Expecter {
	return &ErrorWithStatus_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type ErrorWithStatus
func (_mock *ErrorWithStatus) Error() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ErrorWithStatus_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type ErrorWithStatus_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *ErrorWithStatus_Expecter) Error() *ErrorWithStatus_Error_Call {
	return &ErrorWithStatus_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *ErrorWithStatus_Error_Call) Run(run func()) *ErrorWithStatus_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorWithStatus_Error_Call) Return(s string) *ErrorWithStatus_Error_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ErrorWithStatus_Error_Call) RunAndReturn(run func() string) *ErrorWithStatus_Error_Call {
	_c.Call.Return(run)
	return _c
}

// StatusCode provides a mock function for the type ErrorWithStatus
func (_mock *ErrorWithStatus) StatusCode() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusCode")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// ErrorWithStatus_StatusCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusCode'
type ErrorWithStatus_StatusCode_Call struct {
	*mock.Call
}

// StatusCode is a helper method to define mock.On call
func (_e *ErrorWithStatus_Expecter) StatusCode() *ErrorWithStatus_StatusCode_Call {
	return &ErrorWithStatus_StatusCode_Call{Call: _e.mock.On("StatusCode")}
}

func (_c *ErrorWithStatus_StatusCode_Call) Run(run func()) *ErrorWithStatus_StatusCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorWithStatus_StatusCode_Call) Return(n int) *ErrorWithStatus_StatusCode_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *ErrorWithStatus_StatusCode_Call) RunAndReturn(run func() int) *ErrorWithStatus_StatusCode_Call {
	_c.Call.Return(run)
	return _c
}
