// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gosoline-project/httpserver"
	mock "github.com/stretchr/testify/mock"
)

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler[I any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler[I] {
	mock := &Handler[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Handler is an autogenerated mock type for the Handler type
type Handler[I any] struct {
	mock.Mock
}

type Handler_Expecter[I any] struct {
	mock *mock.Mock
}

func (_m *Handler[I]) EXPECT() *Handler_Expecter[I] {
	return &Handler_Expecter[I]{mock: &_m.Mock}
}

// Handle provides a mock function for the type Handler
func (_mock *Handler[I]) Handle(ctx context.Context, input *I) (httpserver.Response, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 httpserver.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *I) (httpserver.Response, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *I) httpserver.Response); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpserver.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *I) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Handler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Handler_Handle_Call[I any] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - input *I
func (_e *Handler_Expecter[I]) Handle(ctx interface{}, input interface{}) *Handler_Handle_Call[I] {
	return &Handler_Handle_Call[I]{Call: _e.mock.On("Handle", ctx, input)}
}

func (_c *Handler_Handle_Call[I]) Run(run func(ctx context.Context, input *I)) *Handler_Handle_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *I
		if args[1] != nil {
			arg1 = args[1].(*I)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Handler_Handle_Call[I]) Return(response httpserver.Response, err error) *Handler_Handle_Call[I] {
	_c.Call.Return(response, err)
	return _c
}

func (_c *Handler_Handle_Call[I]) RunAndReturn(run func(ctx context.Context, input *I) (httpserver.Response, error)) *Handler_Handle_Call[I] {
	_c.Call.Return(run)
	return _c
}
