// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler[I any, O any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler[I, O] {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Handler[I, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Handler is an autogenerated mock type for the Handler type
type Handler[I any, O any] struct {
	mock.Mock
}

type Handler_Expecter[I any, O any] struct {
	mock *mock.Mock
}

func (_m *Handler[I, O]) EXPECT() *Handler_Expecter[I, O] {
	return &Handler_Expecter[I, O]{mock: &_m.Mock}
}

// Handle provides a mock function for the type Handler
func (_mock *Handler[I, O]) Handle(ctx context.Context, req *http.Request, input *I) (O, error) {
	ret := _mock.Called(ctx, req, input)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 O
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request, *I) (O, error)); ok {
		return returnFunc(ctx, req, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *http.Request, *I) O); ok {
		r0 = returnFunc(ctx, req, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(O)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *http.Request, *I) error); ok {
		r1 = returnFunc(ctx, req, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Handler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Handler_Handle_Call[I any, O any] struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - req *http.Request
//   - input *I
func (_e *Handler_Expecter[I, O]) Handle(ctx any, req any, input any) *Handler_Handle_Call[I, O] {
	return &Handler_Handle_Call[I, O]{Call: _e.mock.On("Handle", ctx, req, input)}
}

func (_c *Handler_Handle_Call[I, O]) Run(run func(ctx context.Context, req *http.Request, input *I)) *Handler_Handle_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 *I
		if args[2] != nil {
			arg2 = args[2].(*I)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Handler_Handle_Call[I, O]) Return(v O, err error) *Handler_Handle_Call[I, O] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Handler_Handle_Call[I, O]) RunAndReturn(run func(ctx context.Context, req *http.Request, input *I) (O, error)) *Handler_Handle_Call[I, O] {
	_c.Call.Return(run)
	return _c
}
