// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewHeaderProvider creates a new instance of HeaderProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHeaderProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *HeaderProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &HeaderProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// HeaderProvider is an autogenerated mock type for the HeaderProvider type
type HeaderProvider struct {
	mock.Mock
}

type HeaderProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *HeaderProvider) EXPECT() *HeaderProvider_Expecter {
	return &HeaderProvider_Expecter{mock: &_m.Mock}
}

// Header provides a mock function for the type HeaderProvider
func (_mock *HeaderProvider) Header() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// HeaderProvider_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type HeaderProvider_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *HeaderProvider_Expecter) Header() *HeaderProvider_Header_Call {
	return &HeaderProvider_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *HeaderProvider_Header_Call) Run(run func()) *HeaderProvider_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HeaderProvider_Header_Call) Return(header http.Header) *HeaderProvider_Header_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *HeaderProvider_Header_Call) RunAndReturn(run func() http.Header) *HeaderProvider_Header_Call {
	_c.Call.Return(run)
	return _c
}
