// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewModifier creates a new instance of Modifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Modifier {
	mock := &Modifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Modifier is an autogenerated mock type for the Modifier type
type Modifier struct {
	mock.Mock
}

type Modifier_Expecter struct {
	mock *mock.Mock
}

func (_m *Modifier) EXPECT() *Modifier_Expecter {
	return &Modifier_Expecter{mock: &_m.Mock}
}

// Struct provides a mock function for the type Modifier
func (_mock *Modifier) Struct(ctx context.Context, v any) error {
	ret := _mock.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, any) error); ok {
		r0 = returnFunc(ctx, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Modifier_Struct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Struct'
type Modifier_Struct_Call struct {
	*mock.Call
}

// Struct is a helper method to define mock.On call
//   - ctx context.Context
//   - v any
func (_e *Modifier_Expecter) Struct(ctx interface{}, v interface{}) *Modifier_Struct_Call {
	return &Modifier_Struct_Call{Call: _e.mock.On("Struct", ctx, v)}
}

func (_c *Modifier_Struct_Call) Run(run func(ctx context.Context, v any)) *Modifier_Struct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Modifier_Struct_Call) Return(err error) *Modifier_Struct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Modifier_Struct_Call) RunAndReturn(run func(ctx context.Context, v any) error) *Modifier_Struct_Call {
	_c.Call.Return(run)
	return _c
}
