// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewNetConn creates a new instance of NetConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetConn {
	mock := &NetConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NetConn is an autogenerated mock type for the NetConn type
type NetConn struct {
	mock.Mock
}

type NetConn_Expecter struct {
	mock *mock.Mock
}

func (_m *NetConn) EXPECT() *NetConn_Expecter {
	return &NetConn_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type NetConn
func (_mock *NetConn) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NetConn_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type NetConn_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *NetConn_Expecter) Close() *NetConn_Close_Call {
	return &NetConn_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *NetConn_Close_Call) Run(run func()) *NetConn_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NetConn_Close_Call) Return(err error) *NetConn_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NetConn_Close_Call) RunAndReturn(run func() error) *NetConn_Close_Call {
	_c.Call.Return(run)
	return _c
}

// LocalAddr provides a mock function for the type NetConn
func (_mock *NetConn) LocalAddr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalAddr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// NetConn_LocalAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalAddr'
type NetConn_LocalAddr_Call struct {
	*mock.Call
}

// LocalAddr is a helper method to define mock.On call
func (_e *NetConn_Expecter) LocalAddr() *NetConn_LocalAddr_Call {
	return &NetConn_LocalAddr_Call{Call: _e.mock.On("LocalAddr")}
}

func (_c *NetConn_LocalAddr_Call) Run(run func()) *NetConn_LocalAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NetConn_LocalAddr_Call) Return(addr net.Addr) *NetConn_LocalAddr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *NetConn_LocalAddr_Call) RunAndReturn(run func() net.Addr) *NetConn_LocalAddr_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type NetConn
func (_mock *NetConn) Read(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetConn_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type NetConn_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - b []byte
func (_e *NetConn_Expecter) Read(b interface{}) *NetConn_Read_Call {
	return &NetConn_Read_Call{Call: _e.mock.On("Read", b)}
}

func (_c *NetConn_Read_Call) Run(run func(b []byte)) *NetConn_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NetConn_Read_Call) Return(n int, err error) *NetConn_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *NetConn_Read_Call) RunAndReturn(run func(b []byte) (int, error)) *NetConn_Read_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteAddr provides a mock function for the type NetConn
func (_mock *NetConn) RemoteAddr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RemoteAddr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// NetConn_RemoteAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteAddr'
type NetConn_RemoteAddr_Call struct {
	*mock.Call
}

// RemoteAddr is a helper method to define mock.On call
func (_e *NetConn_Expecter) RemoteAddr() *NetConn_RemoteAddr_Call {
	return &NetConn_RemoteAddr_Call{Call: _e.mock.On("RemoteAddr")}
}

func (_c *NetConn_RemoteAddr_Call) Run(run func()) *NetConn_RemoteAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NetConn_RemoteAddr_Call) Return(addr net.Addr) *NetConn_RemoteAddr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *NetConn_RemoteAddr_Call) RunAndReturn(run func() net.Addr) *NetConn_RemoteAddr_Call {
	_c.Call.Return(run)
	return _c
}

// SetDeadline provides a mock function for the type NetConn
func (_mock *NetConn) SetDeadline(t time.Time) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NetConn_SetDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDeadline'
type NetConn_SetDeadline_Call struct {
	*mock.Call
}

// SetDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *NetConn_Expecter) SetDeadline(t interface{}) *NetConn_SetDeadline_Call {
	return &NetConn_SetDeadline_Call{Call: _e.mock.On("SetDeadline", t)}
}

func (_c *NetConn_SetDeadline_Call) Run(run func(t time.Time)) *NetConn_SetDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NetConn_SetDeadline_Call) Return(err error) *NetConn_SetDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NetConn_SetDeadline_Call) RunAndReturn(run func(t time.Time) error) *NetConn_SetDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetReadDeadline provides a mock function for the type NetConn
func (_mock *NetConn) SetReadDeadline(t time.Time) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetReadDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NetConn_SetReadDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReadDeadline'
type NetConn_SetReadDeadline_Call struct {
	*mock.Call
}

// SetReadDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *NetConn_Expecter) SetReadDeadline(t interface{}) *NetConn_SetReadDeadline_Call {
	return &NetConn_SetReadDeadline_Call{Call: _e.mock.On("SetReadDeadline", t)}
}

func (_c *NetConn_SetReadDeadline_Call) Run(run func(t time.Time)) *NetConn_SetReadDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NetConn_SetReadDeadline_Call) Return(err error) *NetConn_SetReadDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NetConn_SetReadDeadline_Call) RunAndReturn(run func(t time.Time) error) *NetConn_SetReadDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// SetWriteDeadline provides a mock function for the type NetConn
func (_mock *NetConn) SetWriteDeadline(t time.Time) error {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetWriteDeadline")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NetConn_SetWriteDeadline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetWriteDeadline'
type NetConn_SetWriteDeadline_Call struct {
	*mock.Call
}

// SetWriteDeadline is a helper method to define mock.On call
//   - t time.Time
func (_e *NetConn_Expecter) SetWriteDeadline(t interface{}) *NetConn_SetWriteDeadline_Call {
	return &NetConn_SetWriteDeadline_Call{Call: _e.mock.On("SetWriteDeadline", t)}
}

func (_c *NetConn_SetWriteDeadline_Call) Run(run func(t time.Time)) *NetConn_SetWriteDeadline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NetConn_SetWriteDeadline_Call) Return(err error) *NetConn_SetWriteDeadline_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NetConn_SetWriteDeadline_Call) RunAndReturn(run func(t time.Time) error) *NetConn_SetWriteDeadline_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type NetConn
func (_mock *NetConn) Write(b []byte) (int, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(b)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetConn_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type NetConn_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - b []byte
func (_e *NetConn_Expecter) Write(b interface{}) *NetConn_Write_Call {
	return &NetConn_Write_Call{Call: _e.mock.On("Write", b)}
}

func (_c *NetConn_Write_Call) Run(run func(b []byte)) *NetConn_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *NetConn_Write_Call) Return(n int, err error) *NetConn_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *NetConn_Write_Call) RunAndReturn(run func(b []byte) (int, error)) *NetConn_Write_Call {
	_c.Call.Return(run)
	return _c
}
