// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewNetListener creates a new instance of NetListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNetListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *NetListener {
	mock := &NetListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// NetListener is an autogenerated mock type for the NetListener type
type NetListener struct {
	mock.Mock
}

type NetListener_Expecter struct {
	mock *mock.Mock
}

func (_m *NetListener) EXPECT() *NetListener_Expecter {
	return &NetListener_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function for the type NetListener
func (_mock *NetListener) Accept() (net.Conn, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Accept")
	}

	var r0 net.Conn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (net.Conn, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NetListener_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type NetListener_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
func (_e *NetListener_Expecter) Accept() *NetListener_Accept_Call {
	return &NetListener_Accept_Call{Call: _e.mock.On("Accept")}
}

func (_c *NetListener_Accept_Call) Run(run func()) *NetListener_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NetListener_Accept_Call) Return(conn net.Conn, err error) *NetListener_Accept_Call {
	_c.Call.Return(conn, err)
	return _c
}

func (_c *NetListener_Accept_Call) RunAndReturn(run func() (net.Conn, error)) *NetListener_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Addr provides a mock function for the type NetListener
func (_mock *NetListener) Addr() net.Addr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Addr")
	}

	var r0 net.Addr
	if returnFunc, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}
	return r0
}

// NetListener_Addr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Addr'
type NetListener_Addr_Call struct {
	*mock.Call
}

// Addr is a helper method to define mock.On call
func (_e *NetListener_Expecter) Addr() *NetListener_Addr_Call {
	return &NetListener_Addr_Call{Call: _e.mock.On("Addr")}
}

func (_c *NetListener_Addr_Call) Run(run func()) *NetListener_Addr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NetListener_Addr_Call) Return(addr net.Addr) *NetListener_Addr_Call {
	_c.Call.Return(addr)
	return _c
}

func (_c *NetListener_Addr_Call) RunAndReturn(run func() net.Addr) *NetListener_Addr_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type NetListener
func (_mock *NetListener) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NetListener_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type NetListener_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *NetListener_Expecter) Close() *NetListener_Close_Call {
	return &NetListener_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *NetListener_Close_Call) Run(run func()) *NetListener_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *NetListener_Close_Call) Return(err error) *NetListener_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *NetListener_Close_Call) RunAndReturn(run func() error) *NetListener_Close_Call {
	_c.Call.Return(run)
	return _c
}
