// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/proto"
)

// NewProtobufEncodable creates a new instance of ProtobufEncodable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProtobufEncodable(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProtobufEncodable {
	mock := &ProtobufEncodable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProtobufEncodable is an autogenerated mock type for the ProtobufEncodable type
type ProtobufEncodable struct {
	mock.Mock
}

type ProtobufEncodable_Expecter struct {
	mock *mock.Mock
}

func (_m *ProtobufEncodable) EXPECT() *ProtobufEncodable_Expecter {
	return &ProtobufEncodable_Expecter{mock: &_m.Mock}
}

// ToMessage provides a mock function for the type ProtobufEncodable
func (_mock *ProtobufEncodable) ToMessage() (proto.Message, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToMessage")
	}

	var r0 proto.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (proto.Message, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() proto.Message); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProtobufEncodable_ToMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToMessage'
type ProtobufEncodable_ToMessage_Call struct {
	*mock.Call
}

// ToMessage is a helper method to define mock.On call
func (_e *ProtobufEncodable_Expecter) ToMessage() *ProtobufEncodable_ToMessage_Call {
	return &ProtobufEncodable_ToMessage_Call{Call: _e.mock.On("ToMessage")}
}

func (_c *ProtobufEncodable_ToMessage_Call) Run(run func()) *ProtobufEncodable_ToMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProtobufEncodable_ToMessage_Call) Return(v proto.Message, err error) *ProtobufEncodable_ToMessage_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *ProtobufEncodable_ToMessage_Call) RunAndReturn(run func() (proto.Message, error)) *ProtobufEncodable_ToMessage_Call {
	_c.Call.Return(run)
	return _c
}
