// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/protobuf/proto"
)

// NewProtobufDecodable creates a new instance of ProtobufDecodable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProtobufDecodable(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProtobufDecodable {
	mock := &ProtobufDecodable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProtobufDecodable is an autogenerated mock type for the ProtobufDecodable type
type ProtobufDecodable struct {
	mock.Mock
}

type ProtobufDecodable_Expecter struct {
	mock *mock.Mock
}

func (_m *ProtobufDecodable) EXPECT() *ProtobufDecodable_Expecter {
	return &ProtobufDecodable_Expecter{mock: &_m.Mock}
}

// EmptyMessage provides a mock function for the type ProtobufDecodable
func (_mock *ProtobufDecodable) EmptyMessage() proto.Message {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EmptyMessage")
	}

	var r0 proto.Message
	if returnFunc, ok := ret.Get(0).(func() proto.Message); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.Message)
		}
	}
	return r0
}

// ProtobufDecodable_EmptyMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmptyMessage'
type ProtobufDecodable_EmptyMessage_Call struct {
	*mock.Call
}

// EmptyMessage is a helper method to define mock.On call
func (_e *ProtobufDecodable_Expecter) EmptyMessage() *ProtobufDecodable_EmptyMessage_Call {
	return &ProtobufDecodable_EmptyMessage_Call{Call: _e.mock.On("EmptyMessage")}
}

func (_c *ProtobufDecodable_EmptyMessage_Call) Run(run func()) *ProtobufDecodable_EmptyMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProtobufDecodable_EmptyMessage_Call) Return(v proto.Message) *ProtobufDecodable_EmptyMessage_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *ProtobufDecodable_EmptyMessage_Call) RunAndReturn(run func() proto.Message) *ProtobufDecodable_EmptyMessage_Call {
	_c.Call.Return(run)
	return _c
}

// FromMessage provides a mock function for the type ProtobufDecodable
func (_mock *ProtobufDecodable) FromMessage(message proto.Message) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for FromMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(proto.Message) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProtobufDecodable_FromMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromMessage'
type ProtobufDecodable_FromMessage_Call struct {
	*mock.Call
}

// FromMessage is a helper method to define mock.On call
//   - message proto.Message
func (_e *ProtobufDecodable_Expecter) FromMessage(message interface{}) *ProtobufDecodable_FromMessage_Call {
	return &ProtobufDecodable_FromMessage_Call{Call: _e.mock.On("FromMessage", message)}
}

func (_c *ProtobufDecodable_FromMessage_Call) Run(run func(message proto.Message)) *ProtobufDecodable_FromMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 proto.Message
		if args[0] != nil {
			arg0 = args[0].(proto.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProtobufDecodable_FromMessage_Call) Return(err error) *ProtobufDecodable_FromMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProtobufDecodable_FromMessage_Call) RunAndReturn(run func(message proto.Message) error) *ProtobufDecodable_FromMessage_Call {
	_c.Call.Return(run)
	return _c
}
