// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewResponse creates a new instance of Response. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *Response {
	mock := &Response{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Response is an autogenerated mock type for the Response type
type Response struct {
	mock.Mock
}

type Response_Expecter struct {
	mock *mock.Mock
}

func (_m *Response) EXPECT() *Response_Expecter {
	return &Response_Expecter{mock: &_m.Mock}
}

// Body provides a mock function for the type Response
func (_mock *Response) Body() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Body")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Response_Body_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Body'
type Response_Body_Call struct {
	*mock.Call
}

// Body is a helper method to define mock.On call
func (_e *Response_Expecter) Body() *Response_Body_Call {
	return &Response_Body_Call{Call: _e.mock.On("Body")}
}

func (_c *Response_Body_Call) Run(run func()) *Response_Body_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Response_Body_Call) Return(bytes []byte, err error) *Response_Body_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Response_Body_Call) RunAndReturn(run func() ([]byte, error)) *Response_Body_Call {
	_c.Call.Return(run)
	return _c
}

// ContentType provides a mock function for the type Response
func (_mock *Response) ContentType() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentType")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Response_ContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentType'
type Response_ContentType_Call struct {
	*mock.Call
}

// ContentType is a helper method to define mock.On call
func (_e *Response_Expecter) ContentType() *Response_ContentType_Call {
	return &Response_ContentType_Call{Call: _e.mock.On("ContentType")}
}

func (_c *Response_ContentType_Call) Run(run func()) *Response_ContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Response_ContentType_Call) Return(s string) *Response_ContentType_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Response_ContentType_Call) RunAndReturn(run func() string) *Response_ContentType_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type Response
func (_mock *Response) Header() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// Response_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type Response_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *Response_Expecter) Header() *Response_Header_Call {
	return &Response_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *Response_Header_Call) Run(run func()) *Response_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Response_Header_Call) Return(header http.Header) *Response_Header_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *Response_Header_Call) RunAndReturn(run func() http.Header) *Response_Header_Call {
	_c.Call.Return(run)
	return _c
}

// StatusCode provides a mock function for the type Response
func (_mock *Response) StatusCode() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusCode")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Response_StatusCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusCode'
type Response_StatusCode_Call struct {
	*mock.Call
}

// StatusCode is a helper method to define mock.On call
func (_e *Response_Expecter) StatusCode() *Response_StatusCode_Call {
	return &Response_StatusCode_Call{Call: _e.mock.On("StatusCode")}
}

func (_c *Response_StatusCode_Call) Run(run func()) *Response_StatusCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Response_StatusCode_Call) Return(n int) *Response_StatusCode_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Response_StatusCode_Call) RunAndReturn(run func() int) *Response_StatusCode_Call {
	_c.Call.Return(run)
	return _c
}
