// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	"github.com/gosoline-project/httpserver"
	mock "github.com/stretchr/testify/mock"
)

// NewResponseNegotiator creates a new instance of ResponseNegotiator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResponseNegotiator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResponseNegotiator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &ResponseNegotiator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// ResponseNegotiator is an autogenerated mock type for the ResponseNegotiator type
type ResponseNegotiator struct {
	mock.Mock
}

type ResponseNegotiator_Expecter struct {
	mock *mock.Mock
}

func (_m *ResponseNegotiator) EXPECT() *ResponseNegotiator_Expecter {
	return &ResponseNegotiator_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type ResponseNegotiator
func (_mock *ResponseNegotiator) Render(request *http.Request, anyMoqParam any) (httpserver.Response, error) {
	ret := _mock.Called(request, anyMoqParam)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 httpserver.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request, any) (httpserver.Response, error)); ok {
		return returnFunc(request, anyMoqParam)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request, any) httpserver.Response); ok {
		r0 = returnFunc(request, anyMoqParam)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpserver.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request, any) error); ok {
		r1 = returnFunc(request, anyMoqParam)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResponseNegotiator_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type ResponseNegotiator_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - request *http.Request
//   - anyMoqParam any
func (_e *ResponseNegotiator_Expecter) Render(request any, anyMoqParam any) *ResponseNegotiator_Render_Call {
	return &ResponseNegotiator_Render_Call{Call: _e.mock.On("Render", request, anyMoqParam)}
}

func (_c *ResponseNegotiator_Render_Call) Run(run func(request *http.Request, anyMoqParam any)) *ResponseNegotiator_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResponseNegotiator_Render_Call) Return(response httpserver.Response, err error) *ResponseNegotiator_Render_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *ResponseNegotiator_Render_Call) RunAndReturn(run func(request *http.Request, anyMoqParam any) (httpserver.Response, error)) *ResponseNegotiator_Render_Call {
	_c.Call.Return(run)
	return _c
}
