// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewSseResponseWriter creates a new instance of SseResponseWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSseResponseWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SseResponseWriter {
	mock := &SseResponseWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SseResponseWriter is an autogenerated mock type for the SseResponseWriter type
type SseResponseWriter struct {
	mock.Mock
}

type SseResponseWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *SseResponseWriter) EXPECT() *SseResponseWriter_Expecter {
	return &SseResponseWriter_Expecter{mock: &_m.Mock}
}

// Flush provides a mock function for the type SseResponseWriter
func (_mock *SseResponseWriter) Flush() {
	_mock.Called()
	return
}

// SseResponseWriter_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type SseResponseWriter_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
func (_e *SseResponseWriter_Expecter) Flush() *SseResponseWriter_Flush_Call {
	return &SseResponseWriter_Flush_Call{Call: _e.mock.On("Flush")}
}

func (_c *SseResponseWriter_Flush_Call) Run(run func()) *SseResponseWriter_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SseResponseWriter_Flush_Call) Return() *SseResponseWriter_Flush_Call {
	_c.Call.Return()
	return _c
}

func (_c *SseResponseWriter_Flush_Call) RunAndReturn(run func()) *SseResponseWriter_Flush_Call {
	_c.Run(run)
	return _c
}

// Header provides a mock function for the type SseResponseWriter
func (_mock *SseResponseWriter) Header() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// SseResponseWriter_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type SseResponseWriter_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *SseResponseWriter_Expecter) Header() *SseResponseWriter_Header_Call {
	return &SseResponseWriter_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *SseResponseWriter_Header_Call) Run(run func()) *SseResponseWriter_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SseResponseWriter_Header_Call) Return(header http.Header) *SseResponseWriter_Header_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *SseResponseWriter_Header_Call) RunAndReturn(run func() http.Header) *SseResponseWriter_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type SseResponseWriter
func (_mock *SseResponseWriter) Write(bytes []byte) (int, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SseResponseWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type SseResponseWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - bytes []byte
func (_e *SseResponseWriter_Expecter) Write(bytes interface{}) *SseResponseWriter_Write_Call {
	return &SseResponseWriter_Write_Call{Call: _e.mock.On("Write", bytes)}
}

func (_c *SseResponseWriter_Write_Call) Run(run func(bytes []byte)) *SseResponseWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SseResponseWriter_Write_Call) Return(n int, err error) *SseResponseWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *SseResponseWriter_Write_Call) RunAndReturn(run func(bytes []byte) (int, error)) *SseResponseWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteHeader provides a mock function for the type SseResponseWriter
func (_mock *SseResponseWriter) WriteHeader(statusCode int) {
	_mock.Called(statusCode)
	return
}

// SseResponseWriter_WriteHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteHeader'
type SseResponseWriter_WriteHeader_Call struct {
	*mock.Call
}

// WriteHeader is a helper method to define mock.On call
//   - statusCode int
func (_e *SseResponseWriter_Expecter) WriteHeader(statusCode interface{}) *SseResponseWriter_WriteHeader_Call {
	return &SseResponseWriter_WriteHeader_Call{Call: _e.mock.On("WriteHeader", statusCode)}
}

func (_c *SseResponseWriter_WriteHeader_Call) Run(run func(statusCode int)) *SseResponseWriter_WriteHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *SseResponseWriter_WriteHeader_Call) Return() *SseResponseWriter_WriteHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *SseResponseWriter_WriteHeader_Call) RunAndReturn(run func(statusCode int)) *SseResponseWriter_WriteHeader_Call {
	_c.Run(run)
	return _c
}
