// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewStatusCode creates a new instance of StatusCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusCode(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusCode {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &StatusCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// StatusCode is an autogenerated mock type for the StatusCode type
type StatusCode struct {
	mock.Mock
}

type StatusCode_Expecter struct {
	mock *mock.Mock
}

func (_m *StatusCode) EXPECT() *StatusCode_Expecter {
	return &StatusCode_Expecter{mock: &_m.Mock}
}

// StatusCode provides a mock function for the type StatusCode
func (_mock *StatusCode) StatusCode() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StatusCode")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// StatusCode_StatusCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatusCode'
type StatusCode_StatusCode_Call struct {
	*mock.Call
}

// StatusCode is a helper method to define mock.On call
func (_e *StatusCode_Expecter) StatusCode() *StatusCode_StatusCode_Call {
	return &StatusCode_StatusCode_Call{Call: _e.mock.On("StatusCode")}
}

func (_c *StatusCode_StatusCode_Call) Run(run func()) *StatusCode_StatusCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StatusCode_StatusCode_Call) Return(n int) *StatusCode_StatusCode_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *StatusCode_StatusCode_Call) RunAndReturn(run func() int) *StatusCode_StatusCode_Call {
	_c.Call.Return(run)
	return _c
}
