// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gosoline-project/httpserver"
	mock "github.com/stretchr/testify/mock"
)

// NewTestingSuiteHttpServerRouterAware creates a new instance of TestingSuiteHttpServerRouterAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestingSuiteHttpServerRouterAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestingSuiteHttpServerRouterAware {
	mock := &TestingSuiteHttpServerRouterAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TestingSuiteHttpServerRouterAware is an autogenerated mock type for the TestingSuiteHttpServerRouterAware type
type TestingSuiteHttpServerRouterAware struct {
	mock.Mock
}

type TestingSuiteHttpServerRouterAware_Expecter struct {
	mock *mock.Mock
}

func (_m *TestingSuiteHttpServerRouterAware) EXPECT() *TestingSuiteHttpServerRouterAware_Expecter {
	return &TestingSuiteHttpServerRouterAware_Expecter{mock: &_m.Mock}
}

// SetupHttpServerRouter provides a mock function for the type TestingSuiteHttpServerRouterAware
func (_mock *TestingSuiteHttpServerRouterAware) SetupHttpServerRouter() httpserver.RouterFactory {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetupHttpServerRouter")
	}

	var r0 httpserver.RouterFactory
	if returnFunc, ok := ret.Get(0).(func() httpserver.RouterFactory); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(httpserver.RouterFactory)
		}
	}
	return r0
}

// TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupHttpServerRouter'
type TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call struct {
	*mock.Call
}

// SetupHttpServerRouter is a helper method to define mock.On call
func (_e *TestingSuiteHttpServerRouterAware_Expecter) SetupHttpServerRouter() *TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call {
	return &TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call{Call: _e.mock.On("SetupHttpServerRouter")}
}

func (_c *TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call) Run(run func()) *TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call) Return(routerFactory httpserver.RouterFactory) *TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call {
	_c.Call.Return(routerFactory)
	return _c
}

func (_c *TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call) RunAndReturn(run func() httpserver.RouterFactory) *TestingSuiteHttpServerRouterAware_SetupHttpServerRouter_Call {
	_c.Call.Return(run)
	return _c
}
