// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/gosoline-project/httpserver"
	mock "github.com/stretchr/testify/mock"
)

// NewToHttpserverTestCaseList creates a new instance of ToHttpserverTestCaseList. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToHttpserverTestCaseList(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToHttpserverTestCaseList {
	mock := &ToHttpserverTestCaseList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ToHttpserverTestCaseList is an autogenerated mock type for the ToHttpserverTestCaseList type
type ToHttpserverTestCaseList struct {
	mock.Mock
}

type ToHttpserverTestCaseList_Expecter struct {
	mock *mock.Mock
}

func (_m *ToHttpserverTestCaseList) EXPECT() *ToHttpserverTestCaseList_Expecter {
	return &ToHttpserverTestCaseList_Expecter{mock: &_m.Mock}
}

// ToTestCaseList provides a mock function for the type ToHttpserverTestCaseList
func (_mock *ToHttpserverTestCaseList) ToTestCaseList() []*httpserver.HttpserverTestCase {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToTestCaseList")
	}

	var r0 []*httpserver.HttpserverTestCase
	if returnFunc, ok := ret.Get(0).(func() []*httpserver.HttpserverTestCase); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*httpserver.HttpserverTestCase)
		}
	}
	return r0
}

// ToHttpserverTestCaseList_ToTestCaseList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToTestCaseList'
type ToHttpserverTestCaseList_ToTestCaseList_Call struct {
	*mock.Call
}

// ToTestCaseList is a helper method to define mock.On call
func (_e *ToHttpserverTestCaseList_Expecter) ToTestCaseList() *ToHttpserverTestCaseList_ToTestCaseList_Call {
	return &ToHttpserverTestCaseList_ToTestCaseList_Call{Call: _e.mock.On("ToTestCaseList")}
}

func (_c *ToHttpserverTestCaseList_ToTestCaseList_Call) Run(run func()) *ToHttpserverTestCaseList_ToTestCaseList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToHttpserverTestCaseList_ToTestCaseList_Call) Return(httpserverTestCases []*httpserver.HttpserverTestCase) *ToHttpserverTestCaseList_ToTestCaseList_Call {
	_c.Call.Return(httpserverTestCases)
	return _c
}

func (_c *ToHttpserverTestCaseList_ToTestCaseList_Call) RunAndReturn(run func() []*httpserver.HttpserverTestCase) *ToHttpserverTestCaseList_ToTestCaseList_Call {
	_c.Call.Return(run)
	return _c
}
